# `numpy`

In [1]:
import numpy as np

## Как создать массив в `numpy`?

In [2]:
a = np.array(["1", 2, "汉"])
b = np.array([1, 2, 3], dtype=np.uint16)
c = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=np.float128)

In [3]:
a

array(['1', '2', '汉'], dtype='<U1')

In [4]:
b

array([1, 2, 3], dtype=uint16)

In [5]:
c

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float128)

In [6]:
print(c.shape)

(2, 3)


In [7]:
print(c.dtype)

float128


### Чтобы не писать велосипеды для создания кастомных массивов есть:

In [8]:
np.zeros((2, 2)) # array of all zeroes

array([[0., 0.],
       [0., 0.]])

In [9]:
np.ones((1,2)) # array of all ones

array([[1., 1.]])

In [10]:
np.full((2,2), 42) # constant array

array([[42, 42],
       [42, 42]])

In [11]:
np.eye(3) # diagonal matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.randint(-10, 10, (2, 5)) # array of random elems

array([[ 5, -5, -8, -1, -8],
       [-7, -5, -7,  9,  3]])

## Индексирование и слайсы

In [13]:
a = np.random.randint(0, 100, size=(5, 10))
print(a)

[[74 35 75 25 25 98 40 47 11 74]
 [33 42 82 60 97 27  6 66 26 52]
 [84 43 35  2 88 21 27 49 41 74]
 [72 92 35 59 79 36 49 27 24 38]
 [80 46 80 87 14 61 29 24 44 70]]


In [14]:
a[0]

array([74, 35, 75, 25, 25, 98, 40, 47, 11, 74])

In [15]:
a[0, 1] # the same as a[0][1]

35

In [16]:
# Можно делать слайсы по осям. Получим 2-ой столбец матрицы:
a[:, 1]

array([35, 42, 43, 92, 46])

In [17]:
# выведем все элементы, кроме последнего, из предпоследнего столбца:
a[:-1, -2]

array([11, 26, 41, 24])

In [18]:
# а теперь каждый 2-ой элемент (начиная с 0-ого индекса) последней строчки:
a[-1, ::2]

array([80, 80, 14, 29, 44])

In [19]:
# каждый 2-ой элемент (начиная с 1-ого индекса) последней строчки:
a[-1, 1::2]

array([46, 87, 61, 24, 70])

In [20]:
# все четные элементы массива:
a[a > 0]

array([74, 35, 75, 25, 25, 98, 40, 47, 11, 74, 33, 42, 82, 60, 97, 27,  6,
       66, 26, 52, 84, 43, 35,  2, 88, 21, 27, 49, 41, 74, 72, 92, 35, 59,
       79, 36, 49, 27, 24, 38, 80, 46, 80, 87, 14, 61, 29, 24, 44, 70])

In [21]:
# 1-ая и 5-ая строчки массива:
a[np.array([0, 4])]

array([[74, 35, 75, 25, 25, 98, 40, 47, 11, 74],
       [80, 46, 80, 87, 14, 61, 29, 24, 44, 70]])

### Для присваивания тоже работает!

In [22]:
a

array([[74, 35, 75, 25, 25, 98, 40, 47, 11, 74],
       [33, 42, 82, 60, 97, 27,  6, 66, 26, 52],
       [84, 43, 35,  2, 88, 21, 27, 49, 41, 74],
       [72, 92, 35, 59, 79, 36, 49, 27, 24, 38],
       [80, 46, 80, 87, 14, 61, 29, 24, 44, 70]])

In [23]:
a[1:-1, :] = 1
a

array([[74, 35, 75, 25, 25, 98, 40, 47, 11, 74],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [80, 46, 80, 87, 14, 61, 29, 24, 44, 70]])

In [25]:
a[:, 1:3] = np.arange(2)
a

array([[74,  0,  1, 25, 25, 98, 40, 47, 11, 74],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [80,  0,  1, 87, 14, 61, 29, 24, 44, 70]])

## Операции с `np.array`

In [41]:
a = np.random.randint(low=0, high=100, size=(3, 4))
b = np.random.randint(low=0, high=100, size=(3, 4))
c = np.random.randint(low=0, high=100, size=4)
d = 42

print(f"a: {a}", end="\n\n")
print(f"b: {b}", end="\n\n")
print(f"c: {c}", end="\n\n")

a: [[42 59 84 41]
 [23 78 23 28]
 [75 64 72 33]]

b: [[51 91 40 65]
 [67 86 51 14]
 [16 85 60  1]]

c: [ 4 59 68 11]



In [27]:
print(a.reshape((2, 6))) # the same as a.shape = (1, 6)

[[98 63 89 15 38  7]
 [37 68 75 36 90 39]]


In [28]:
print(a.T)

[[98 38 75]
 [63  7 36]
 [89 37 90]
 [15 68 39]]


In [29]:
a + b

array([[186, 135, 156,  60],
       [132,  56,  76,  72],
       [140, 104, 163, 108]])

In [30]:
a - b

array([[ 10,  -9,  22, -30],
       [-56, -42,  -2,  64],
       [ 10, -32,  17, -30]])

In [31]:
# какое это умножение?
a * b

array([[8624, 4536, 5963,  675],
       [3572,  343, 1443,  272],
       [4875, 2448, 6570, 2691]])

In [32]:
# а это?
a @ b.T

array([[19798, 15830, 18186],
       [ 9387,  5630, 10339],
       [16977, 12480, 16584]])

In [33]:
a / b

array([[ 1.11363636,  0.875     ,  1.32835821,  0.33333333],
       [ 0.40425532,  0.14285714,  0.94871795, 17.        ],
       [ 1.15384615,  0.52941176,  1.23287671,  0.56521739]])

In [34]:
a = np.array([[5, 4], [7, 8]])
for_pow = np.array([2, 3])

a ** for_pow

array([[ 25,  64],
       [ 49, 512]])

In [35]:
np.sqrt(b)

array([[9.38083152, 8.48528137, 8.18535277, 6.70820393],
       [9.69535971, 7.        , 6.244998  , 2.        ],
       [8.06225775, 8.24621125, 8.54400375, 8.30662386]])

In [36]:
np.sum(b)

733

In [37]:
np.sum(b, axis=0)

array([247, 189, 179, 118])

In [38]:
np.min(a[0])

4

In [42]:
np.vstack([a, b])

array([[42, 59, 84, 41],
       [23, 78, 23, 28],
       [75, 64, 72, 33],
       [51, 91, 40, 65],
       [67, 86, 51, 14],
       [16, 85, 60,  1]])

In [43]:
np.hstack([a, b])

array([[42, 59, 84, 41, 51, 91, 40, 65],
       [23, 78, 23, 28, 67, 86, 51, 14],
       [75, 64, 72, 33, 16, 85, 60,  1]])

### Волшебный `np.vectorize`

In [44]:
pow_2 = lambda x: x ** 2

In [45]:
pow_2(np.array([2, 3, 4]))

array([ 4,  9, 16])

In [46]:
pow_2([2, 3, 4])

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [47]:
pow_2_vec = np.vectorize(pow_2)
pow_2_vec([2, 3, 4])

array([ 4,  9, 16])

### Немного про broadcasting

In [48]:
a + d

array([[ 84, 101, 126,  83],
       [ 65, 120,  65,  70],
       [117, 106, 114,  75]])

In [49]:
a + c

array([[ 46, 118, 152,  52],
       [ 27, 137,  91,  39],
       [ 79, 123, 140,  44]])

In [50]:
b - d

array([[  9,  49,  -2,  23],
       [ 25,  44,   9, -28],
       [-26,  43,  18, -41]])

#### Задание (*): с помощью `np.random.randint` создайте два массива (`x` и `y`) с элементами в диапазоне [-1000, 1000], размерами (12, 42) и (42, 12), соответственно. Найдите самое большое положительное нечетное число последнего столбца произведения матриц `x` и `y`.

In [ ]:
x = np.random.randint(-1000, 1000, (12, 42))
y = np.random.randint(-1000, 1000, (42, 12))

tmp = (x @ y)[:, -1]
print(tmp[(tmp % 2 == 1) & (tmp > 0)].max())

### Задание: написать решалку линейных уравнений

In [ ]:
# Линейные уравнения можно решать следующим образом: Ax = y, где A-матрица. 
# A^(T)Ax=A^(T)y
# x=(A^(T)A)^(-1)A^(T)y
# давайте сделаем свою решалку таких уравнений
# HINT: np.linalg...

def solution_finder(A, y):
    return np.linalg.inv(A) @ y

### Задание: решить систему методом [Крамера](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%9A%D1%80%D0%B0%D0%BC%D0%B5%D1%80%D0%B0)

In [61]:
#TODO решить систему методом Крамера
#HINT: np.linalg.det
import copy

def cramer_solver(A, b):
    x = np.zeros((1, A.shape[1]))
    d0 = np.linalg.det(A)
    for i in range(A.shape[1]):
        tmp = copy.deepcopy(A)
        tmp[:, i] = b
        x[i] = np.linalg.det(tmp) / d0
    return x

## Few more things:

### `np.random.seed()`

In [57]:
for i in range(5):
    arr = np.arange(5)  # [0, 1, 2, 3, 4]
    np.random.seed(1)  # Reset random state
    np.random.shuffle(arr)  # Shuffle!
    print(arr)

[2 1 4 0 3]
[2 1 4 0 3]
[2 1 4 0 3]
[2 1 4 0 3]
[2 1 4 0 3]


In [58]:
np.random.seed(3)
print(np.random.random())

np.random.seed(3)
print(np.random.random())

0.5507979025745755
0.5507979025745755


### `np.isclose()`

In [59]:
np.float128(1 / 3) * 3 == 1

False

In [60]:
np.isclose(np.float128(1 / 3) * 3, 1)

True

---

# scipy.sparse

In [62]:
from scipy.sparse import csr_matrix
from sys import getsizeof

In [66]:
a = np.random.randint(0, 2, (1, 1_000_000))
print(getsizeof(a))

a_csr = csr_matrix(a)
print(getsizeof(a_csr))

8000112
56


In [67]:
a.mean()

0.5002

#### Или можно вот так вот создать:

In [69]:
values = list(range(1, 11))
row_idxs = [0, 1, 2, 0, 1, 2, 0, 1, 2, 3]
column_idxs = [4, 3, 2, 1, 1, 3, 3, 4, 0, 0]

csr_improvisation = csr_matrix((values, (row_idxs, column_idxs)))
csr_improvisation.toarray()

array([[ 0,  4,  0,  7,  1],
       [ 0,  5,  0,  2,  8],
       [ 9,  0,  3,  6,  0],
       [10,  0,  0,  0,  0]], dtype=int64)